project:
  type: website
  output-dir: docs

website:
  title: "Viet Hung Nguyen Cao"
  navbar:
    search: false

format:
  html:
    mainfont: Helvetica Neue, Arial, "Hiragino Kaku Gothic ProN" "Hiragino Sans", "BIZ UDPGothic", Meiryo, sans-serif
    fontsize: 13pt
    theme: 
      - materia
      - custom.scss
    toc: true
    toc-title: " "



