---
title: Research
---

**To war or not to war: Backing down after a fait accompli in Japan (under review)**

Abstract: The risk of fait-accompli in the East China Sea is on the rise and poses a serious threat to peace and stability in the region. If it happens, can Japan back down to avoid war? This paper argues that the Japanese government can use a number of reasons to justify their decision to de-escalate, in order to limit the domestic audience cost. Using evidence from a survey experiment in Japan, I found that emphasizing a threat of war from China, the weaker power position vis-a-vis China, using the international court to settle the dispute and mediation from the United Nations will help limit the audience cost faced. Only emphasizing economic sanctions does not reduce audience costs. I also found a strong negative correlation between political beliefs and the approval rating for the Japanese government when they back down. 

**Does the US Really Embolden Allies? Evidence from a Survey Experiment in Japan (with Kudo Yasuki) (under review)**

Abstract: Do patrons’ signals of security commitments embolden junior partners? The literature on military alliances suggests that this might be the case: supportive gestures by patrons could motivate junior partners to adopt more aggressive postures in their own disputes than they would without such support. While the theoretical logic is compelling when considering states as unitary actors, it is less clear if this logic applies to the domestic public that may have differing interests from leaders. To complement this gap, we conducted a survey experiment in Japan, a close US ally with a territorial dispute with China, to explore the impact of US presidential signals on public support for adopting aggressive policies towards China. We find that US signals increase the credibility of US military intervention in territorial disputes; however no evidence of an emboldenment effect is found—public support for escalatory policies does not increase accordingly. Additionally, we find that US signals do not encourage the public to punish leaders backing down after announcing aggressive policies. These findings challenge the conventional understanding of an important effect of alliance politics.

**Kinmen, kinsmen? An experiment of fait accompli in Taiwan**

Abstract: Fait accompli is a strategy in which challenger states seeking to incrementally revise the territorial status quo. However, states who wish to use this strategy face a difficult task of assuring the victim states that their territorial goals are indeed limited. This paper attempts to investigate the extent to which the public in the victim state reacts to assurance signals from the challenger state after a fait accompli, as well as how the public reacts to their government conceding the territory without retaliation. By conducting an online survey experiment in Taiwan, I found that the Taiwanese public are against retaliating fait accompli with forces, regardless of assuring signals from China. However, the Taiwanese public also showed dissatisfaction if there is no retaliation, regardless of the excuses given by the government. The results contribute to the literature on assurance, and challenge existing works on mitigating audience costs.

**Examining Vietnamese attitude toward China: Moving beyond the anti-China framing (with Phan Xuan Dung and Richard Turcsanyi)**

Abstract: Common narratives hold that the Vietnamese public harbors predominantly negative feelings toward China due to past Chinese aggression, ongoing disputes in the South China Sea, and China’s economic and strategic influence over Vietnam. While there is truth in these assertions, our paper argues that they are too simplistic to fully capture the Vietnamese perception of China. Utilizing a new public opinion survey dataset, we show that Vietnamese people’s attitude towards China is more balanced and nuanced than often portrayed. Vietnamese perception of China varies across demographics (e.g. age, region, and education) and topics (e.g. China’s actions in the South China Sea, Chinese culture and the 1979 Sino-Vietnamese border war). Both the media and scholarly work should move beyond the ‘anti-China’ framing and examine the diversity of views that we underscore in this paper. A more nuanced understanding of how Vietnam perceives China is not only beneficial to the literature on Vietnam-China relations but also informative for the making of foreign policy in Vietnam.

**An alliance assurance conundrum: Experiments of fait accompli in Japan and the Philippines**
